server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
#    consul注册中心地址
  cloud:
    consul:
      host: 192.168.0.111
      port: 8500
      discovery:
        hostname: 192.168.0.145
        service-name: ${spring.application.name}