spring:
  profiles:
    active:  dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-server-test
---
spring:
  profiles: dev
  application:
    name: springcloud-config-server-dev
