spring:
  application:
    name: config-client
  profiles: test
  
eureka:
  client:
    service-url:
      #注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka/
      
---
spring:
  application:
    name: config-client-dev5
  profiles: dev 
  
eureka:
  client:
    service-url:
      #注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka/      
